#
#server:
#  port: 8080
#  servlet:
#    context-path: /
#    encoding:
#      charset: utf-8
#      enabled: true
#    session:
#      timeout: 60m
#    


#내장톰캣 구동안하고
spring:
  main:
    web-application-type: none
    

# CentralStation    172.16.81.180   
ip: localhost   

#socket
qtPort: 5050
csPort: 5051

ftp:
  port: 2121
  user: kyu
  pwd: 1234